### ISSUE TITLE
какво прави това

### ISSUE THREAD

**Issue by DNaydenov** [bmestanov/OOP#2]
https://github.com/bmestanov/OOP/blob/821d3835047b79f81b1463ff22bad05fa80c6660/week03/NumSum.h#L17

**Comment by bmestanov** [comment]
Казва на компилатора да не генерира operator=, т.е не можеш да напишеш нещо като
```c++
NumSum a,b;
a = b; // Няма такъв оператор
```

**Comment by DNaydenov** [comment]
ясно, значи изтрива даже и оператора по подразбиране, който е
